// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicationSite.Api.Data;

#nullable disable

namespace PublicationSite.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801101645_AddUserAvailability")]
    partial class AddUserAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KeywordPublication", b =>
                {
                    b.Property<Guid>("KeywordsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PublicationsId")
                        .HasColumnType("char(36)");

                    b.HasKey("KeywordsId", "PublicationsId");

                    b.HasIndex("PublicationsId");

                    b.ToTable("PublicationKeywords", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("PublicationResearchArea", b =>
                {
                    b.Property<Guid>("PublicationsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResearchAreasId")
                        .HasColumnType("char(36)");

                    b.HasKey("PublicationsId", "ResearchAreasId");

                    b.HasIndex("ResearchAreasId");

                    b.ToTable("PublicationResearchAreas", (string)null);
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ActivityHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("OnBehalfOfUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PublicationContainerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OnBehalfOfUserId");

                    b.HasIndex("PublicationContainerId");

                    b.ToTable("ActivityHistoryEntries");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("int");

                    b.Property<string>("AzureObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("InstitutionalId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OnBehalfOfUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OnBehalfOfUserId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Committee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MinApprovalsRequired")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PublicationId")
                        .IsUnique();

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CommitteeMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("DecisionComments")
                        .HasColumnType("text");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommitteeId", "UserId")
                        .IsUnique();

                    b.ToTable("CommitteeMembers");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CommitteeMemberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Affiliation")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CommitteeMemberProfiles");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CommitteeRoleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CommitteeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.ToTable("CommitteeRoleConfigs");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CoordinatorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAvailableForAssignment")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CoordinatorProfiles");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CoordinatorDecisionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CoordinatorDecisionComments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinalDecisionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HeadOfDepartmentComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HeadOfDepartmentReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsRequiredPerCoordinator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsRequiredPerSupervisor")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PublicationContainerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SupervisorDecisionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SupervisorDecisionComments")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublicationContainerId")
                        .IsUnique();

                    b.ToTable("EthicsApprovals");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsApprovalRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EthicsApprovalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EthicsDocumentRequirementId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EthicsDocumentRequirementId");

                    b.HasIndex("EthicsApprovalId", "EthicsDocumentRequirementId")
                        .IsUnique();

                    b.ToTable("EthicsApprovalRequirements");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsDeclaration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PublicationContainerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("StudentResponse")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicationContainerId")
                        .IsUnique();

                    b.ToTable("EthicsDeclarations");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EthicsApprovalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EthicsDocumentRequirementId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ReviewComments")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EthicsApprovalId");

                    b.HasIndex("EthicsDocumentRequirementId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("EthicsDocuments");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsDocumentRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EthicsDocumentRequirements");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.HeadOfDepartmentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HeadOfDepartmentProfiles");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ProposalAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CoordinatorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SupervisorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("ProposalAssignments");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ProposalSupervisorSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("SelectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SupervisorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("ProposalId", "SupervisorId")
                        .IsUnique();

                    b.ToTable("ProposalSupervisorSelections");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PublicationContainerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PublicationType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PublicationContainerId")
                        .IsUnique();

                    b.HasIndex("PublishedByUserId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.PublicationContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CoordinatorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CoordinatorProfileId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentPipeline")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredCommitteeApprovals")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredExternalCommitteeMembers")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredInternalCommitteeMembers")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSupervisorId");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("CoordinatorProfileId");

                    b.HasIndex("StudentId");

                    b.ToTable("PublicationContainers");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.PublicationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("text");

                    b.Property<string>("SupplementaryFilesPath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("PublicationId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PublicationVersions");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ResearchArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResearchAreas");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ResearchProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PublicationContainerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PublicationContainerId");

                    b.ToTable("ResearchProposals");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicationVersionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReviewerType")
                        .HasColumnType("int");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PublicationVersionId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cohort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Orcid")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("PreferredSupervisorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Programme")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StudentIdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PreferredSupervisorId");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.SupervisorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AreasOfExpertise")
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResearchInterests")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SupervisorProfiles");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("UserInvitations");
                });

            modelBuilder.Entity("ResearchAreaStudentProfile", b =>
                {
                    b.Property<Guid>("ResearchAreasId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("char(36)");

                    b.HasKey("ResearchAreasId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("StudentResearchAreas", (string)null);
                });

            modelBuilder.Entity("KeywordPublication", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.Publication", null)
                        .WithMany()
                        .HasForeignKey("PublicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublicationResearchArea", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Publication", null)
                        .WithMany()
                        .HasForeignKey("PublicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ResearchArea", null)
                        .WithMany()
                        .HasForeignKey("ResearchAreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ActivityHistoryEntry", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "OnBehalfOfUser")
                        .WithMany()
                        .HasForeignKey("OnBehalfOfUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PublicationSite.Api.Entities.PublicationContainer", "PublicationContainer")
                        .WithMany("ActivityHistory")
                        .HasForeignKey("PublicationContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("OnBehalfOfUser");

                    b.Navigation("PublicationContainer");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "OnBehalfOfUser")
                        .WithMany()
                        .HasForeignKey("OnBehalfOfUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("OnBehalfOfUser");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Committee", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.Publication", "Publication")
                        .WithOne("Committee")
                        .HasForeignKey("PublicationSite.Api.Entities.Committee", "PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CommitteeMember", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Committee", "Committee")
                        .WithMany("Members")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Committee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CommitteeMemberProfile", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "User")
                        .WithOne("CommitteeMemberProfile")
                        .HasForeignKey("PublicationSite.Api.Entities.CommitteeMemberProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CommitteeRoleConfig", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Committee", "Committee")
                        .WithMany("RoleConfigs")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CoordinatorProfile", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Department", "Department")
                        .WithMany("Coordinators")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "User")
                        .WithOne("CoordinatorProfile")
                        .HasForeignKey("PublicationSite.Api.Entities.CoordinatorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsApproval", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.PublicationContainer", "PublicationContainer")
                        .WithOne("EthicsApproval")
                        .HasForeignKey("PublicationSite.Api.Entities.EthicsApproval", "PublicationContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicationContainer");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsApprovalRequirement", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.EthicsApproval", "EthicsApproval")
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("EthicsApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.EthicsDocumentRequirement", "EthicsDocumentRequirement")
                        .WithMany()
                        .HasForeignKey("EthicsDocumentRequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EthicsApproval");

                    b.Navigation("EthicsDocumentRequirement");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsDeclaration", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.PublicationContainer", "PublicationContainer")
                        .WithOne("EthicsDeclaration")
                        .HasForeignKey("PublicationSite.Api.Entities.EthicsDeclaration", "PublicationContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicationContainer");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsDocument", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.EthicsApproval", "EthicsApproval")
                        .WithMany("Documents")
                        .HasForeignKey("EthicsApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.EthicsDocumentRequirement", "EthicsDocumentRequirement")
                        .WithMany("Documents")
                        .HasForeignKey("EthicsDocumentRequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EthicsApproval");

                    b.Navigation("EthicsDocumentRequirement");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.HeadOfDepartmentProfile", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Department", "Department")
                        .WithOne("HeadOfDepartment")
                        .HasForeignKey("PublicationSite.Api.Entities.HeadOfDepartmentProfile", "DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "User")
                        .WithOne("HeadOfDepartmentProfile")
                        .HasForeignKey("PublicationSite.Api.Entities.HeadOfDepartmentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Notification", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ProposalAssignment", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ResearchProposal", "Proposal")
                        .WithOne("Assignment")
                        .HasForeignKey("PublicationSite.Api.Entities.ProposalAssignment", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinator");

                    b.Navigation("Proposal");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ProposalSupervisorSelection", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ResearchProposal", "Proposal")
                        .WithMany("SupervisorSelections")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proposal");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Publication", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.PublicationContainer", "PublicationContainer")
                        .WithOne("Publication")
                        .HasForeignKey("PublicationSite.Api.Entities.Publication", "PublicationContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PublicationContainer");

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.PublicationContainer", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "AssignedSupervisor")
                        .WithMany()
                        .HasForeignKey("AssignedSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.CoordinatorProfile", null)
                        .WithMany("AssignedContainers")
                        .HasForeignKey("CoordinatorProfileId");

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedSupervisor");

                    b.Navigation("Coordinator");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.PublicationVersion", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Publication", "Publication")
                        .WithMany("Versions")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publication");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ResearchProposal", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.PublicationContainer", "PublicationContainer")
                        .WithMany("Proposals")
                        .HasForeignKey("PublicationContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicationContainer");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Review", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.PublicationVersion", "PublicationVersion")
                        .WithMany("Reviews")
                        .HasForeignKey("PublicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "ReviewerUser")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PublicationVersion");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.StudentProfile", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "PreferredSupervisor")
                        .WithMany()
                        .HasForeignKey("PreferredSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("PublicationSite.Api.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("PreferredSupervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.SupervisorProfile", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Department", "Department")
                        .WithMany("Supervisors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "User")
                        .WithOne("SupervisorProfile")
                        .HasForeignKey("PublicationSite.Api.Entities.SupervisorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.SystemSetting", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.UserInvitation", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.ApplicationUser", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("InvitedByUser");

                    b.Navigation("RevokedByUser");
                });

            modelBuilder.Entity("ResearchAreaStudentProfile", b =>
                {
                    b.HasOne("PublicationSite.Api.Entities.ResearchArea", null)
                        .WithMany()
                        .HasForeignKey("ResearchAreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PublicationSite.Api.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ApplicationUser", b =>
                {
                    b.Navigation("CommitteeMemberProfile");

                    b.Navigation("CoordinatorProfile");

                    b.Navigation("HeadOfDepartmentProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("SupervisorProfile");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Committee", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("RoleConfigs");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.CoordinatorProfile", b =>
                {
                    b.Navigation("AssignedContainers");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Department", b =>
                {
                    b.Navigation("Coordinators");

                    b.Navigation("HeadOfDepartment");

                    b.Navigation("Students");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsApproval", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("RequiredDocuments");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.EthicsDocumentRequirement", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.Publication", b =>
                {
                    b.Navigation("Committee");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.PublicationContainer", b =>
                {
                    b.Navigation("ActivityHistory");

                    b.Navigation("EthicsApproval");

                    b.Navigation("EthicsDeclaration");

                    b.Navigation("Proposals");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.PublicationVersion", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PublicationSite.Api.Entities.ResearchProposal", b =>
                {
                    b.Navigation("Assignment");

                    b.Navigation("SupervisorSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
